name: "Validate Gradle Wrapper"
on:
  pull_request: { }
  push:
    branches: [ main, develop ]

permissions: {}

jobs:
  validation:
    name: "Validation"
    runs-on: ubuntu-latest
    # No concurrency required, this is a prerequisite to other actions and should run every time.
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: gradle/wrapper-validation-action@f9c9c575b8b21b6485636a91ffecd10e558c62f6 # v3.5.0
