name: Validate Git LFS

on: [pull_request]

permissions: {}

jobs:
  build:
    runs-on: ubuntu-latest
    name: Validate
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          lfs: 'true'
          persist-credentials: false

      - run: |
          ./tools/validate_lfs.sh
